# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: push-CI

env:
  DEV_DEFAULT_KEY: ${{ secrets.DEV_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
  PROD_DEFAULT_KEY: ${{ secrets.PROD_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
  VERSION: 2.01

on:
  push:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.01]
  repository_dispatch:

concurrency: CI-2.01

jobs:
  build-commit:
    runs-on: ubuntu-latest
    env:
      RESOURCE_NAME: ${{ github.event.client_payload.resourceName }}
      TRIGGER_REPO: ${{ github.event.client_payload.repo }}
      TRIGGER_SHA: ${{ github.event.client_payload.SHA }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-dev libxslt-dev libxslt1-dev python3-dev python3-lxml libxml2-utils
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Build
        run: |
          ./gen.sh

      - name: 'Setup git config'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: 'Commit changes'
        run: |
          RESP=$(git add codelist_rules.json -v)
          if [[ $RESP == "" ]]; then
            echo "No changes to commit"
            exit 0
          else
            if [[ $TRIGGER_REPO == "" ]]; then
              TRIGGERED_BY="${{ github.actor }} on push"
            else
              TRIGGERED_BY=$($TRIGGER_REPO $TRIGGER_SHA)
            fi
            git commit -m "codelist_rules.json updated by GitHub Actions triggered by $TRIGGERED_BY"
            git push origin version-2.01
          fi

  cache-codelist-rules-dev:
    needs: build-commit
    runs-on: ubuntu-latest
    env:
      TRIGGER_REPO: ${{ github.event.client_payload.repo }}
      TRIGGER_SHA: ${{ github.event.client_payload.SHA }}
    steps:
      - name: 'Event Information'
        run: |
          echo "Event '${{ github.event.action }}' for $RESOURCE_NAME received from $TRIGGER_REPO and commit sha $TRIGGER_SHA"

      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: POST codelist_rules.json to func-iati-redis-cacher-dev
        run: | 
          FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './codelist_rules.json')
          echo $FILE_COMMIT_SHA
          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
          --location --request POST 'https://func-iati-redis-cacher-dev.azurewebsites.net/api/pvt/cache?key=codelistRules'$VERSION'&commitsha='$FILE_COMMIT_SHA \
          --header 'x-functions-key: '$DEV_DEFAULT_KEY \
          --header 'Content-Type: application/json' \
          --data-binary '@./codelist_rules.json' \
          --output curl_out.txt \
          --silent )
          echo $HTTP_CODE
          if [[ $HTTP_CODE != '200' ]] ; then
            echo "Reponse is not 200 from func-iati-redis-cacher-dev, check error logs"
            cat curl_out.txt
            exit 1
          fi

  cache-codelist-rules-PROD:
    needs: cache-codelist-rules-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: POST codelist_rules.json to func-iati-redis-cacher-PROD
        run: | 
          FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './codelist_rules.json')
          echo $FILE_COMMIT_SHA
          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
          --location --request POST 'https://func-iati-redis-cacher-prod.azurewebsites.net/api/pvt/cache?key=codelistRules'$VERSION'&commitsha='$FILE_COMMIT_SHA \
          --header 'x-functions-key: '$PROD_DEFAULT_KEY \
          --header 'Content-Type: application/json' \
          --data-binary '@./codelist_rules.json' \
          --output curl_out.txt \
          --silent )
          echo $HTTP_CODE
          if [[ $HTTP_CODE != '200' ]] ; then
            echo "Reponse is not 200 from func-iati-redis-cacher-PROD, check error logs"
            cat curl_out.txt
            exit 1
          fi
